//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHangV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Carts = new HashSet<Cart>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Addresss { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Tel { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Cart> Carts { get; set; }
    }
}
